apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  #amqp://guest:guest@my-rabbit.southeastasia.azurecontainer.io:5672/
  host: YW1xcDovL2d1ZXN0Omd1ZXN0QG15LXJhYmJpdC5zb3V0aGVhc3Rhc2lhLmF6dXJlY29udGFpbmVyLmlvOjU2NzIv
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
spec:
  scaleTargetRef:
    name: app1
  minReplicaCount: 1
  pollingInterval: 10
  cooldownPeriod: 10
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: orderQueue
      mode: QueueLength
      value: "20"
      metricName: order-metrics #optional. Generated value would be `rabbitmq-custom-testqueue`
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn