apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  type: LoadBalancer
  ports:
  ## Available on load-balancer port 8082
  - port: 8082
    targetPort: 80
  selector:
    app: azure-vote-front