apiVersion: v1
kind: Pod
metadata:
  name: pod-volume1
  labels:
    name: pod-volume1
spec:
  volumes:
    - name: vol1
      hostPath:
          path: /home/mahendra/mydata

  containers:
  - name: myapp
    image: mahendrshinde/myweb:latest
    volumeMounts:
      - name: vol1
        mountPath: "/data"
        readOnly: false
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
